
export type Role = 'User' | 'Club Admin' | 'PPMK';

export const permissionsByRole: Record<Role, string[]> = {
  User: [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'view:orders',
    'view:tickets',
  ],
  'Club Admin': [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'action:create-event',
    'action:manage-rsvps',
    'view:orders',
    'view:tickets',
    'view:admin',
  ],
  PPMK: [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'action:create-event',
    'action:manage-rsvps',
    'action:approve-club',
    'action:manage-users',
    'action:override',
    'view:orders',
    'view:tickets',
    'view:admin',
  ],
};
