export type Role = 'Student' | 'Club Admin' | 'University Admin';

export const permissionsByRole: Record<Role, string[]> = {
  Student: [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'view:orders',
    'view:tickets',
  ],
  'Club Admin': [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'action:create-event',
    'action:manage-rsvps',
    'view:orders',
    'view:tickets',
  ],
  'University Admin': [
    'view:dashboard',
    'view:clubs',
    'view:events',
    'view:recommendations',
    'view:settings',
    'view:profile',
    'action:request-membership',
    'action:rsvp',
    'action:create-event',
    'action:manage-rsvps',
    'action:approve-club',
    'action:manage-users',
    'view:orders',
    'view:tickets',
  ],
};
