type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  university: University
}

type University @table {
  name: String!
  domain: String!
  createdAt: Timestamp!
  location: String
}

type Club @table {
  name: String!
  university: University!
  description: String!
  createdAt: Timestamp!
  admin: User!
  contactEmail: String
  websiteUrl: String
}

type Membership @table(key: ["user", "club"]) {
  user: User!
  club: Club!
  status: String! # PENDING, APPROVED, REJECTED
  joinedAt: Timestamp!
  role: String
}

type Event @table {
  club: Club!
  title: String!
  startTime: Timestamp!
  endTime: Timestamp!
  createdAt: Timestamp!
  description: String
  location: String
  rsvpRequired: Boolean
}

type Attendance @table(key: ["user", "event"]) {
  user: User!
  event: Event!
  attendedAt: Timestamp!
  rsvpStatus: String # GOING, MAYBE, NOT_GOING
}