name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome to ELMO! Thank you for creating your first issue. The team will review it as soon as possible. Please make sure you've followed our issue template and provided all the necessary information to help us understand your request or bug report."
        pr-message: "🎉 Thanks for submitting your first pull request to ELMO! Our team will review your changes soon. Please ensure you've followed our contribution guidelines (see CONTRIBUTING.md) and that all tests are passing. We appreciate your efforts to improve our student club management platform!"
